Implement REST API Server for Model Registry
opendatahub-io/model-registry-bf4-kf pull request #108
Opened 2023-10-27 12:53 UTC by tarilabs

Raising this as Draft to discuss early some directions/found issues/talking points:
- Use of Robot framework ( Tony )
- Uncovered problem and prosposed solution for OpenAPI endpoint (@dhirajsb )
- ~~@lampajr will be adding helpful `goverter`s here~~
added with 13402e1

Resolves #59 

## Description
Satisfies acceptance criteria from #59

## How Has This Been Tested?
- `docker run -p 8081:8080 --env METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb --volume ./test/bdd:/tmp/shared gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0`
- `make build && ./model-registry proxy`
- Invoking `.robot` tests

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-10-27 13:02 UTC, tarilabs reviewed
Comment for Tony and Radim

2023-10-27 13:02 UTC, tarilabs commented on test/robot/UserStory.robot
> +        And Should be equal    ${r["name"]}    ${name}
Demonstrate use of Robot Framework, by implementing (and covering) a User Story from PM going via the REST impl in this PR.

![Screenshot 2023-10-27 at 14 57 23](https://github.com/opendatahub-io/model-registry/assets/1699252/a3aceb73-a6cb-4f48-915e-b7d7497a6630)

Tony, would you deem a sensible use of Robot Framework?
If yes, I'd extend this also beyond "User Story" also to cover for the expected logical mapping of the behind-the-scenes of MLMD (something less of interest of PM and more of us as implementors).

2023-10-27 13:14 UTC, tarilabs commented on internal/server/openapi/api_model_registry_service_service.go
>  func (s *ModelRegistryServiceAPIService) CreateModelVersionArtifact(ctx context.Context, modelversionId string, artifact model.Artifact) (ImplResponse, error) {
This is something we believe uncovered as we started working on this wirings, and would appreciate your confirmation on our proposed solution below @dhirajsb please?

## Problem statement

In the OpenAPI, _this_ endpoint `CreateModelVersionArtifact` is missing to align to `createModelArtifact`.

Specifically, this endpoint is having as input a generic-but-not-specialized `#/components/schemas/Artifact` 

https://github.com/opendatahub-io/model-registry/blob/52d2151c14eca541ff8187df9df73c2ed60659e6/api/openapi/model-registry.yaml#L417

Missing to provide `artifactType : "ModelArtifact"` in the payload creates a server panic in the code which was autogenerated:

```
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:1868 +0xb0
panic({0x102d10cc0?, 0x1033ad3b0?})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:920 +0x26c
github.com/opendatahub-io/model-registry/internal/server/openapi.AssertArtifactRequired({0x140004b0140?})
	/Users/mmortari/git/model-registry/internal/server/openapi/type_asserts.go:19 +0x5c
github.com/opendatahub-io/model-registry/internal/server/openapi.(*ModelRegistryServiceAPIController).CreateModelVersionArtifact(0x140000ce150, {0x12a33c040, 0x1400020aac0}, 0x140000cc200)
	/Users/mmortari/git/model-registry/internal/server/openapi/api_model_registry_service.go:379 +0x150
net/http.HandlerFunc.ServeHTTP(0x102d09b00?, {0x12a33c040?, 0x1400020aac0?}, 0x140000c0005?)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2136 +0x38
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x140000a2480, {0x12a33c040, 0x1400020aac0}, 0x140000cc200)
	/Users/mmortari/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x270
net/http.HandlerFunc.ServeHTTP(0x140000d01e0?, {0x12a33c040?, 0x1400020aac0?}, 0x140000cc200?)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2136 +0x38
github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x12a33c040, 0x1400020aac0}, 0x140000cc200)
	/Users/mmortari/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x19c
net/http.HandlerFunc.ServeHTTP(0x140000cc100?, {0x12a33c040?, 0x1400020aac0?}, 0x102246054?)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2136 +0x38
github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1({0x102e30cb0, 0x14000324000}, 0x140000cc100)
	/Users/mmortari/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/middleware/logger.go:54 +0x120
net/http.HandlerFunc.ServeHTTP(0x102e32818?, {0x102e30cb0?, 0x14000324000?}, 0x1033ae530?)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2136 +0x38
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x140000a2480, {0x102e30cb0, 0x14000324000}, 0x140000cc000)
	/Users/mmortari/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x2bc
net/http.serverHandler.ServeHTTP({0x102e2e710?}, {0x102e30cb0?, 0x14000324000?}, 0x6?)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x14000192090, {0x102e327e0, 0x140000b0db0})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 1
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/net/http/server.go:3086 +0x4cc
```

Further, as a result is output again `Artifact` which is not consistent with `createModelArtifact`

## Proposed solution

We propose 2 modification to simplify and make this endpoint consistent:

A. For this endpoint, have as input the `ModelArtifactCreate` as it's the case with `createModelArtifact`:
ie.
make it analogous to:

https://github.com/opendatahub-io/model-registry/blob/52d2151c14eca541ff8187df9df73c2ed60659e6/api/openapi/model-registry.yaml#L73-L80

B. For this endpoint, have as output the `ModelArtifact` as it's the case with `createModelArtifact`:
ie.
make it analogous to:

https://github.com/opendatahub-io/model-registry/blob/52d2151c14eca541ff8187df9df73c2ed60659e6/api/openapi/model-registry.yaml#L83-L85

2023-10-29 23:51 UTC, dhirajsb commented on internal/server/openapi/api_model_registry_service_service.go
>  func (s *ModelRegistryServiceAPIService) CreateModelVersionArtifact(ctx context.Context, modelversionId string, artifact model.Artifact) (ImplResponse, error) {
Looks like I missed adding the default value for the discriminator property in `ModelArtifact` like so:
```yaml
    ModelArtifact:
      description: An ML model artifact.
      type: object
      allOf:
        -
          $ref: '#/components/schemas/BaseArtifact'
        -
          $ref: '#/components/schemas/ModelArtifactCreate'
        -
          type: object
          properties:
            artifactType:
              type: string
              default: "model-artifact"
```

2023-10-30 11:20 UTC, tarilabs commented on internal/server/openapi/api_model_registry_service_service.go
>  func (s *ModelRegistryServiceAPIService) CreateModelVersionArtifact(ctx context.Context, modelversionId string, artifact model.Artifact) (ImplResponse, error) {
We applied the suggestion you suggested: https://github.com/opendatahub-io/model-registry/pull/108#discussion_r1375551218
here: 6de0597

We found it did not resolve the panic error detailed https://github.com/opendatahub-io/model-registry/pull/108#discussion_r1374559417 anyway 

At first, we thought it could have been some bug of the openapi generator, as by its doc the case is not explicilty supported: https://github.com/OpenAPITools/openapi-generator/blob/8827da801274a71c88ea2e19538540c6d8c13108/docs/generators/go-server.md?plain=1#L211

But after further analysis, we realized that the methods:
- `Assert{{classname}}Required()`
- `Assert{{classname}}Constraints()`

are out-of-sync even when issuing the Make "gen/openapi-server"
as those are ingnored ( they are generated as part of the "models" )
and seems to us the file `type_asserts.go` is never autogenerated and was possibly a manual-handcrafted file (despite its header).

We are now considering using a custom `model.mustache` template so to have Asserts method regenerated (when manually/explicitly invoking gen/openapi-server) so to have them up-to-date.

2023-10-30 11:27 UTC, tarilabs commented on internal/server/openapi/api_model_registry_service_service.go
> +	// }
Note to self: once Asserts are refreshed, make sure this check is enabled before merging the PR

2023-10-31 16:55 UTC, tarilabs commented
@isinyaaa here is a suggestion looking specifically at commit: https://github.com/opendatahub-io/model-registry/pull/108/commits/60756dfc3de2ea0bbb897dc819667c56f167deeb

The [test](https://github.com/opendatahub-io/model-registry/pull/108/commits/60756dfc3de2ea0bbb897dc819667c56f167deeb#diff-e8fee46a378c137ad9fcf43a5bf83180c8f1471b617032f57e48179647f921da) intent is to demonstrate the Logical Model mapping, in this case going REST as input, and [checking on the backend gRPC MLMD](https://github.com/opendatahub-io/model-registry/pull/108/commits/60756dfc3de2ea0bbb897dc819667c56f167deeb#diff-e8fee46a378c137ad9fcf43a5bf83180c8f1471b617032f57e48179647f921daR31-R56).

Kindly consider if you could implement the "robot keywords" in the stubbed file:
https://github.com/opendatahub-io/model-registry/blob/60756dfc3de2ea0bbb897dc819667c56f167deeb/test/robot/MRviaPython.resource#L1-L5
using your client.

When you have some time you could try it out and let us know if that seems to work for you too, please?

 @tonyxrmdavidson and @rkubis : you can reference the commit https://github.com/opendatahub-io/model-registry/pull/108/commits/60756dfc3de2ea0bbb897dc819667c56f167deeb for a concrete demo of what we also shared today.
Do you think it would be possible to parametrize the `.robot` file,
so to execute it once using `MRviaREST.resource` [file](https://github.com/opendatahub-io/model-registry/pull/108/commits/60756dfc3de2ea0bbb897dc819667c56f167deeb#diff-0286f776d2bc501a899733f626ad40cd7c3f63aedb0dc1d05f5c2664ebf8b046),
and a second time using an alternative `.resource` import,
so in the end we would be able to keep 1 "assertion" way but checking going via REST-as-input and Python-as-input, please?

2023-11-06 09:42 UTC, lampajr requested changes

2023-11-06 09:42 UTC, lampajr commented on cmd/proxy.go
> +	}
We should add this defer to ensure cleaning up the connection resource, wdyt?
```suggestion
	if err != nil {
		log.Fatalf("Error dialing connection to mlmd server %s: %v", mlmdAddr, err)
		return err
	}
	defer conn.Close()
```

2023-11-06 09:56 UTC, lampajr approved these changes
It looks really great. 
Thanks a lot @tarilabs !

2023-11-07 09:55 UTC, tarilabs commented on internal/server/openapi/api_model_registry_service_service.go
> +	// }
this was de-commented and part of code now.

2023-11-07 09:55 UTC, merged