Basic Unit Test for PutArtifactType logic
opendatahub-io/model-registry-bf4-kf pull request #18
Opened 2023-09-22 14:09 UTC by tarilabs

introduce basic go test Unit Test
for testing logic of gRPC PutArtifactType

## Description

## How Has This Been Tested?
```
$ go test -timeout 30s -run PutArtifactType github.com/opendatahub-io/model-registry/internal/server -v
=== RUN   TestPutArtifactType
    grpc_server_test.go:63: Should PutArtifactType: type_id:1
    grpc_server_test.go:66: Should PutArtifactTypeResponse.TypeId an ID > 0: type_id:1
--- PASS: TestPutArtifactType (0.01s)
=== RUN   TestPutArtifactTypeNoNameFailure
    grpc_server_test.go:95: Should error on PutArtifactType with Request missing Name: rpc error: code = Internal desc = server panic: runtime error: invalid memory address or nil pointer dereference
--- PASS: TestPutArtifactTypeNoNameFailure (0.00s)
PASS
ok  	github.com/opendatahub-io/model-registry/internal/server	0.608s
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work (see above)

2023-09-22 15:05 UTC, lampajr approved these changes, later dismissed
lgtm

2023-09-22 15:05 UTC, lampajr commented on internal/server/grpc_server_test.go
> +		t.Logf("Should error on PutArtifactType with Request missing Name: %v", err)
```suggestion
		t.Logf("Expected error on PutArtifactType with Request missing Name: %v", err)
```

2023-09-22 15:17 UTC, isinyaaa commented on internal/server/grpc_server_test.go
> +		t.Errorf("Should expect DB connection: %v", err)
`Should expect` in error messages sounds confusing. How about:

```suggestion
		t.Errorf("Expected DB connection: %v", err)
```

2023-09-22 15:24 UTC, isinyaaa commented on internal/server/grpc_server_test.go
> +	}
If both messages are the same, why don't we
```suggestion
	t.Logf("Should PutArtifactTypeResponse.TypeId an ID > 0: %v", response)
	if *response.TypeId <= 0 {
		t.Fail()
	}
```

2023-09-22 15:26 UTC, isinyaaa commented on internal/server/grpc_server_test.go
> +		t.Errorf("Should error on PutArtifactType with Request missing Name: %v, %v", response, err)
Here, `err` should be `nil`, so why print it?

2023-09-22 15:26 UTC, isinyaaa reviewed
lgtm aside from error messages. I don't get why we're using "should ..." here every time. Some of them don't make any sense to me.

2023-09-22 15:27 UTC, tarilabs commented on internal/server/grpc_server_test.go
> +	}
I just adopted "test styleguide" from a course I've followed which tends to reuse the verbatim but use Logf Vs Errorf 🤷

2023-09-22 15:29 UTC, tarilabs commented
> I don't get why we're using "should ..." here every time. Some of them don't make any sense to me.

👉  https://github.com/opendatahub-io/model-registry/pull/18#discussion_r1334532493

> Also: please use the imperative on the commit message.

I have used title within 50 chars, newline, description; I am afraid I did not understand what you meant here. Do you have an article to point me to, please.

2023-09-22 15:29 UTC, isinyaaa commented on internal/server/grpc_server_test.go
> +	}
I tend to be against this because DRY on string makes a lot of sense -- one less place to update in case the test changes, and it's not totally obvious that both strings are the exact same.

2023-09-22 15:34 UTC, antisaling commented
> > I don't get why we're using "should ..." here every time. Some of them don't make any sense to me.
> 
> 👉 [#18 (comment)](https://github.com/opendatahub-io/model-registry/pull/18#discussion_r1334532493)

EDIT: I see it now. Can you link to this style guide so we can all understand where you're coming from? @tarilabs 

> > Also: please use the imperative on the commit message.
> 
> I have used title within 50 chars, newline, description; I am afraid I did not understand what you meant here. Do you have an article to point me to, please.

This one is pretty good: https://cbea.ms/git-commit/
@lampajr @dhirajsb if you haven't read it, please check it out as well

2023-09-22 15:40 UTC, tarilabs commented
> Also: please use the imperative on the commit message.

👉  21743b5

2023-09-22 16:06 UTC, dhirajsb commented
In general unit tests for each API are not a good idea. They have a very limited scope and therefore a very short period where they are useful. They can also cause a lot of repetition in test setup. 

For the OpenShift Connectors Control Plane API, we built an extensive suite of BDD style integration API call  _scenarios_, which tested multiple APIs in various sequences. Those tests were a lot more useful because they exercised APIs in real world use cases and served as excellent regression tests. 
We don't have to create an extensive test suite and all the scenarios right away, but we should start building a test runner like I mentioned in #14. We can start with simple scenarios that look like unit tests, but grow and become more complex over time.

2023-09-25 05:57 UTC, tarilabs commented on internal/server/grpc_server_test.go
> +	}
I will adopt this other "styleguide" as I also tend to agree with DRY, until I get more clear the majority preference for the group

2023-09-26 08:01 UTC, lampajr approved these changes

2023-09-26 16:40 UTC, dhirajsb requested changes
Re-use this as a unit test for the DB service handler. That way it's a quick and easy unit test and we leave integration testing to python scripts.

2023-09-26 20:11 UTC, isinyaaa commented
The last commit could've been a fixup. If you do squash this, please remove that message.

2023-09-27 09:36 UTC, tarilabs commented
> Re-use this as a unit test for the DB service handler. That way it's a quick and easy unit test and we leave integration testing to python scripts.

I think we discussed about having small unit test for "surface contacts" or "core capabilities" and serving as smoke testing was helpful.
This could have served as a small smoke/unit test in that sense.
It seems however that there is no way to have a change-of-mind about this.
Noted. ✍️ 

Rejected with https://github.com/opendatahub-io/model-registry/pull/18#pullrequestreview-1644747578 , closing PR.

2023-09-27 09:36 UTC, closed without merging