Serve correct grpc listener
opendatahub-io/model-registry-bf4-kf pull request #19
Opened 2023-09-22 14:50 UTC by lampajr

## Description

This change includes the folowing fixes:
* Set correct `grpcListener` on grpcServer serve invocation
* Remove useless lister parameter on `grpcListenerServer` and `graphQlListenerServer`

## How Has This Been Tested?

This has been tested starting the grpc server using `make run/server` and executing `test/python/test_mlmetadata.py`, without this change the script was stuck at the first grpc call, whereas with this change the script completes.

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-09-22 14:52 UTC, tarilabs approved these changes
seen live, agree; well spotted (imho) ! 👍

2023-09-22 14:52 UTC, tarilabs commented on cmd/serve.go
> +		return grpcServer.Serve(grpcListener)
🔭

2023-09-22 15:10 UTC, isinyaaa approved these changes
lgtm!

2023-09-22 20:34 UTC, dhirajsb requested changes
The listener is not useless. :smile:  It's meant to filter gRPC calls.
The server is being _cute_ by using the same port for both gRPC and GraphQL calls. 

I've opened another issue #22  to change the mux to gin and use two separate ports for gRPC and GraphQL to avoid the filtering issue altogether.

2023-09-22 20:51 UTC, lampajr commented
> The listener is not useless. :smile:  It's meant to filter gRPC calls.
> The server is being _cute_ by using the same port for both gRPC and GraphQL calls. 
> 
> I've opened another issue #22  to change the mux to gin and use two separate ports for gRPC and GraphQL to avoid the filtering issue altogether. 

I meant it was useless in that functions, the parameter (listener) was not used at all - that's why I removed them.

2023-09-22 21:08 UTC, dhirajsb approved these changes
lgtm for now
If you can take on the new issue to switch to gin-gonic that'll solve any potential issues with grpc and cmux.

2023-09-22 21:12 UTC, merged

2023-09-23 21:42 UTC, lampajr commented
> lgtm for now
> If you can take on the new issue to switch to gin-gonic that'll solve any potential issues with grpc and cmux. 

thanks @dhirajsb ! 
Sure i will take that issue as well 💪