New(workflow): Run Robot Framework tests with every push
opendatahub-io/model-registry-bf4-kf pull request #208
Opened 2023-11-28 15:42 UTC by rkubis

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-12-04 10:02 UTC, lampajr reviewed
Hey @rkubis, I took a quick look at this PR as I think this could be very helpful to run it every push/pr, thanks a lot!

I left some comments, let me know what you think :)

2023-12-04 10:02 UTC, lampajr commented on .github/workflows/run-robot-tests.yaml
> +        run: pip install ml-metadata robotframework robotframework-requests pyyaml
May I suggest to export these libraries into a separated `requirements.txt` and then install it using `pip install -r test/robot/requirements.txt` ? In this way we can use the same command to install those libraries locally and furthermore I think it is much more maintainable.

2023-12-04 10:02 UTC, lampajr commented on .github/workflows/run-robot-tests.yaml
> +on: [push]
I think we should also add `pull_request` to run it on every PR too, wdyt?

2023-12-04 10:05 UTC, lampajr commented on .github/workflows/run-robot-tests.yaml
> +on: [push]
This way we can also check the workflow runs as expected in this PR

2023-12-04 10:05 UTC, rkubis commented on .github/workflows/run-robot-tests.yaml
> +        run: pip install ml-metadata robotframework robotframework-requests pyyaml
Thanks @lampajr, I agree!

2023-12-04 10:06 UTC, rkubis commented on .github/workflows/run-robot-tests.yaml
> +on: [push]
@lampajr Sure, good idea :)

2023-12-04 10:07 UTC, lampajr commented on .github/workflows/run-robot-tests.yaml
> +on: [push]
I was thinking something like https://github.com/opendatahub-io/model-registry/blob/259b39320953bf05942dcec1fb5ec74f7eb5d4a7/.github/workflows/build.yml#L3-L17

2023-12-04 10:13 UTC, tarilabs commented on .github/workflows/run-robot-tests.yaml
> +        run: pip install ml-metadata robotframework robotframework-requests pyyaml
+1 and kindly consider `ml-metadata==1.14.0`

2023-12-04 10:20 UTC, rkubis commented on .github/workflows/run-robot-tests.yaml
> +        run: pip install ml-metadata robotframework robotframework-requests pyyaml
@tarilabs Thanks, it is done now 👍

2023-12-04 10:21 UTC, tonyxrmdavidson commented on .github/workflows/run-robot-tests.yaml
> +        run: pip install ml-metadata robotframework robotframework-requests pyyaml
> +1 and kindly consider `ml-metadata==1.14.0`

Will there be a need to test different versions of ml-metadata?

2023-12-04 10:21 UTC, rkubis commented on .github/workflows/run-robot-tests.yaml
> +on: [push]
@lampajr I used the same settings for `pull_request`, but for `push` I changed it from `main` to `*`.

2023-12-04 10:29 UTC, tonyxrmdavidson commented
/lgtm

2023-12-04 10:30 UTC, tonyxrmdavidson approved these changes
/lgtm

2023-12-04 11:03 UTC, lampajr requested changes
Adding the suggestion below, tests should fail for:
```
[ ERROR ] Error in file '/home/alampare/repos/model-registry/test/robot/MRkeywords.resource' on line 5: Importing library '/home/alampare/repos/model-registry/test/robot/ModelRegistry.py' failed: AttributeError: module 'model_registry' has no attribute 'client'
Traceback (most recent call last):
  File "/home/alampare/repos/model-registry/test/robot/ModelRegistry.py", line 10, in <module>
    class ModelRegistry(mr.client.ModelRegistry):
PYTHONPATH:
  /home/alampare/repos/model-registry/test/robot
  /home/alampare/miniconda3/envs/model-registry/bin
  /home/alampare/miniconda3/envs/model-registry/lib/python39.zip
  /home/alampare/miniconda3/envs/model-registry/lib/python3.9
  /home/alampare/miniconda3/envs/model-registry/lib/python3.9/lib-dynload
  /home/alampare/miniconda3/envs/model-registry/lib/python3.9/site-packages
  /home/alampare/repos/model-registry/clients/python/src
```

As there was a change in the Python api [1], therefore the Robot tests should be adapated as well. This error is a good example of why adding this Robot test automation in every PR is a very good enhancement :)

[1] https://github.com/opendatahub-io/model-registry/pull/209/

2023-12-04 11:03 UTC, lampajr commented on .github/workflows/run-robot-tests.yaml
> +        run: robot test/robot
IIUC from https://github.com/opendatahub-io/model-registry/pull/158 to properly test all configs we should also add `TEST_MODE=Python robot test/robot/MRandLogicalModel.robot` in order to test the same `.robot` test using python library. Is my understading right @tarilabs ?

```suggestion
        run: | 
          robot test/robot
          TEST_MODE=Python robot test/robot/MRandLogicalModel.robot
```

2023-12-04 13:12 UTC, tarilabs commented on .github/workflows/run-robot-tests.yaml
> +        run: robot test/robot
+1

2023-12-11 10:46 UTC, tonyxrmdavidson commented
/retest

2023-12-13 00:03 UTC, isinyaaa reviewed
Hey, Radim, thanks a lot for the changes :)

While I like the idea of having comments, I would also argue that a yaml file has a pretty simple syntax, and interleaving every line with comments is not really necessary.
It's also pretty common for comments to get outdated, or to be simply wrong, and this can hurt maintainability.
Either way I won't block you on this, it's just my 2c ;).

I've just submitted a fix for the failing imports, let's see if we can get this working (and passing!)

2023-12-13 21:09 UTC, isinyaaa commented
I think the Python tests should pass cleanly now, can you rebase?

2023-12-14 09:09 UTC, lampajr approved these changes
lgtm for now, we might improve it in further iterations if needed.

As @isinyaaa raised I agree that most of the comments in the workflow could be removed but up to you @rkubis , not a blocker for me

2023-12-14 09:23 UTC, rkubis commented
@isinyaaa Thanks for fixing Python tests for me! :)

2023-12-14 09:25 UTC, rkubis commented
@isinyaaa @lampajr Yeah, I know that there is a lot more comments than expected 😄  I will leave it there for now and I can remove it in the next iteration. Thanks for feedback!

2023-12-14 22:14 UTC, tarilabs commented
I notice this is approved and all tests a re passing.

@tonyxrmdavidson @rkubis just double check: I would assume you have merge rights to merge this when suitable; if you need someone to merge it on your behalf don't hesitate to ping/tag

2023-12-15 08:31 UTC, rkubis commented
@tarilabs Thanks :) I don't have merge permission (yet), maybe @tonyxrmdavidson already have.

2024-01-17 13:13 UTC, lampajr commented
Is there any update on this front? can we get this merged?

2024-01-17 13:38 UTC, rkubis commented
@lampajr The update is that I got permission to merge this PR on my own right now 😄

2024-01-17 13:38 UTC, merged