py: using Testcontainers and test strategy as go
opendatahub-io/model-registry-bf4-kf pull request #225
Opened 2023-12-04 12:52 UTC by tarilabs

Resolves #224

## Description
Using Testcontainers for Python and testing analogously to what we done as testing strategy on go Core layer 

### Caveats
Unfortunately this would make it unavailable in docker-in-docker setups such as DevContainers. While this problem can be circumvented by manually raising a MLMD server in the host docker, the problem appears to be slowness in FS reactivity when deleting the sqlite file. Considering the ideal solution is likely more about avoiding emulation and rely on gRPC (see recent document submitted to the group), I would conclude this PR and Testcontainers based approach is still the better solution.

## How Has This Been Tested?
```
pytest -v -x -s
```
✅ `40 passed in 14.07s`

Since I'm on M-chip I've used the .toml wheel using only grpc connection. I'd appreciate some 👀 from some other contributors using Intel: @lampajr can you give it a spin when possible, please? @isinyaaa can you give it a spin from the remote server when possible, please?

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-12-04 12:54 UTC, tarilabs commented
edit: Correction, seems like `pytest --cov --cov-config=pyproject.toml --cov-report=xml` from `nox` in GitHub Action is not accounting `testcontainers` despite being listed in the dev dependency from toml 🤔 
@isinyaaa @dtrifiro can you kindly check the GHA setup accordingly, please?

2023-12-04 13:17 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
🔍 ☝️  when mentioned:

> Since I'm on M-chip I've used the .toml wheel using only grpc connection. I'd appreciate some 👀 from some other contributors using Intel: @lampajr can you give it a spin when possible, please? @isinyaaa can you give it a spin from the remote server when possible, please?

2023-12-04 15:47 UTC, dtrifiro commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
Looking at the fixture implementation, it looks kinda clutterered. How about trying https://pypi.org/project/pytest-docker/?

2023-12-04 16:18 UTC, tarilabs commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
That's a possibility; the reason for adopting TestContainers is that we're using it already on the Go side, hence for alignment.

In any case, this is discussion we can have separately, currently my main doubt here is as summarized in: https://github.com/opendatahub-io/model-registry/pull/225#issuecomment-1838576589

2023-12-04 16:38 UTC, lampajr commented
> edit: Correction, seems like `pytest --cov --cov-config=pyproject.toml --cov-report=xml` from `nox` in GitHub Action is not accounting `testcontainers` despite being listed in the dev dependency from toml 🤔 @isinyaaa @dtrifiro can you kindly check the GHA setup accordingly, please?

IIUC it should be enough to change https://github.com/opendatahub-io/model-registry/blob/0621864cea0d438df528afd1aac0bd6eb39fc0c2/clients/python/noxfile.py#L52
to 
```python
 session.install("coverage[toml]", "pytest", "pytest-cov", "pygments", "testcontainers") 
```

2023-12-04 16:40 UTC, lampajr commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
fwiw I tried all three approaches, and all of them worked (all tests green) on Intel :rocket:

2023-12-04 17:05 UTC, tarilabs commented
Edit: codecov now working

2023-12-05 10:24 UTC, lampajr submitted a review, later dismissed
lgtm

2023-12-05 22:14 UTC, isinyaaa requested changes
Thanks for the change Matteo :)

I noticed we haven't enabled linting on tests, so I'd like to ask you to wait before merging this and then rebase on top of #231 when that's merged so we can iron out some things before merging. Is that OK?

2023-12-05 22:14 UTC, antisaling commented on clients/python/tests/conftest.py
> +    return request.config.rootdir + '/../..'
I don't think this function is necessary, I also didn't find `rootdir` in their API docs so I'd use the safer [`rootpath`](https://docs.pytest.org/en/latest/reference/reference.html#pytest.Config.rootpath).

2023-12-05 22:14 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    return request.config.rootdir + '/../..'
Per the previous comment, as `rootpath` is a `Path` object, it's possible to do:

```suggestion
def model_registry_root(request):
    return (request.config.rootpath / '../..').resolve()  # resolves to absolute path
```

you can use the same trick on other parts as well, printing this will also be fine :)

2023-12-05 22:14 UTC, antisaling commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
nit: we could skip this log

2023-12-05 22:14 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +        raise FileExistsError(f"The file {sqlite_db_file} already exists; make sure to cancel it before running these tests.")
Can't we use a temporary file for the DB?

2023-12-05 22:18 UTC, isinyaaa commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
I agree that `pytest-docker` would probably lead to a simpler approach, is there any special reason we want to align both implementations on this?

2023-12-06 13:05 UTC, tarilabs commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
As mentioned, this brings alignment on Integration Testing strategy and "infrastructure" if compared to Go side.

Another thing which later did not find in `pytest-docker` is ryuk container orchestration, which is typically helpful when performing test locally. But please let me know if I missed.

I've tested on M2 Mac, this works; Andrea tested on Intel works; on GHA is green. Is there something not working on someone else platform motivating a requested-change on the (allegedly already-working) solution presented in this PR which I missed, please? 🤔

2023-12-06 13:06 UTC, tarilabs commented
> I noticed we haven't enabled linting on tests, so I'd like to ask you to wait before merging this and then rebase on top of #231 when that's merged so we can iron out some things before merging. Is that OK?

sure, noted. Will hold this merge to rebase on #231

2023-12-06 13:07 UTC, tarilabs commented on clients/python/tests/conftest.py
> +        raise FileExistsError(f"The file {sqlite_db_file} already exists; make sure to cancel it before running these tests.")
We can evaluate this in a subsequent PR since we're also making analogous consideration on IT infra on Go side. We should as well consider using cmd line option in place of the pb config file then.

2023-12-06 13:10 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
you mean line 28 or simply all the prints? Those were helpful during debugging and by default I understand they are suppressed unless you launch with `-s`. Do you want to use an alternative logging framework/call?

2023-12-06 13:16 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    return request.config.rootdir + '/../..'
per https://github.com/opendatahub-io/model-registry/pull/225/files/09c0674ced24aa2a45d3eaaa28c905667115a543#diff-31172aa4bf9754641d05923f27755c9b5886c54e7e74ad170ab81b940e580d7e

2023-12-10 17:09 UTC, tarilabs commented
requesting review after rebasing per original request in https://github.com/opendatahub-io/model-registry/pull/225#pullrequestreview-1766186790

2023-12-11 14:21 UTC, antisaling commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
I mean the log on line 26, as it's just `../../` from the last one.

2023-12-11 14:23 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    if os.path.exists(sqlite_db_file):
```suggestion
    sqlite_db_file = model_registry_root_dir / "test/config/ml-metadata/metadata.sqlite.db"
    if sqlite_db_file.exists():
```

2023-12-11 14:27 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +        os.system(f"rm {model_registry_root_dir}/test/config/ml-metadata/metadata.sqlite.db") # noqa governed test
```suggestion
        os.system(f"rm {sqlite_db_file}") # noqa governed test
```
?

2023-12-11 14:28 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
can you clarify the purpose of this autouse fixture?

2023-12-11 14:33 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
Sure.
After each test, remove the SQLite file.
Analogously how we done on Go side with @lampajr

2023-12-11 14:35 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
but that I found helpful with `-s` to make sure it was pointing to the expected directory?
I can remove it, but personally I found it helpful (considering it is displayed only with opt-in with `-s` on test launch).

2023-12-11 14:37 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
After each test *using the `plain_wrapper`, to clarify

2023-12-11 14:57 UTC, dtrifiro commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
Why not use a fixture to provide the sqlite db and then do the teardown after the yield?

2023-12-11 15:14 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
> Why not use a fixture to provide the sqlite db and then do the teardown after the yield?

unless I missed something, that's exactly what the lines
https://github.com/opendatahub-io/model-registry/pull/225/files#diff-31172aa4bf9754641d05923f27755c9b5886c54e7e74ad170ab81b940e580d7eR22-R23

above are doing.

With the difference the provision is session scope.
While the removal of the SQLite file is done after each test (using the plain_wrapper).

This allow us to have the Container spin up once, while a new SQLite file is created by the MLMD server at each test.

This approach also on Go layer allowed us to save some time if compared to shutdown and reprovision of the MLMD container.

2023-12-11 15:28 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
ok I see better now, we could remove line 24

2023-12-11 15:29 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
```suggestion
    model_registry_root_dir = model_registry_root(request)
    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
```

2023-12-11 15:29 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
noted in https://github.com/opendatahub-io/model-registry/pull/225/files#r1422653146

2023-12-11 15:30 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print("Assuming this is the Model Registry root directory:", model_registry_root_dir)
done with https://github.com/opendatahub-io/model-registry/pull/225/commits/845f5c7c172e0f0eb1abb52db56056c8a63d45d3

2023-12-12 12:27 UTC, dtrifiro commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
How about using the `tmp_dir` fixture to provide a new workspace for each test?

2023-12-12 13:03 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    request.addfinalizer(teardown)
> How about using the `tmp_dir` fixture to provide a new workspace for each test?

Yes, that would a possible future improvement also on Go side, but we can do that in subsquent PRs as mentioned in https://github.com/opendatahub-io/model-registry/pull/225#discussion_r1417271106

2023-12-12 21:30 UTC, isinyaaa commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
I don't know if I missed something but I keep getting this prompt after each test when running with `-s`:
<img width="1272" alt="image" src="https://github.com/opendatahub-io/model-registry/assets/39812919/39f212e8-d293-4e77-8a9c-6ab5d8268cc9">

2023-12-12 21:34 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    container.with_env("METADATA_STORE_SERVER_CONFIG_FILE", "/tmp/shared/conn_config.pb") # noqa this is target in container
nit:

```suggestion
    shared_volume = model_registry_root_dir / "test/config/ml-metadata"
    sqlite_db_file = shared_volume / "metadata.sqlite.db"
    if sqlite_db_file.exists():
        msg = f"The file {sqlite_db_file} already exists; make sure to cancel it before running these tests."
        raise FileExistsError(msg)
    container = DockerContainer("gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0")
    container.with_exposed_ports(8080)
    container.with_volume_mapping(shared_volume, "/tmp/shared", "rw") # noqa this is file target in container
    container.with_env("METADATA_STORE_SERVER_CONFIG_FILE", "/tmp/shared/conn_config.pb") # noqa this is target in container
```

2023-12-12 22:30 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
that's very strange, never got them 🤔 
@lampajr would you mind retest again this PR, using `poetry run test -x -s` please?

2023-12-12 22:32 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    container.with_env("METADATA_STORE_SERVER_CONFIG_FILE", "/tmp/shared/conn_config.pb") # noqa this is target in container
I see, you want to reuse the `shared_volume` ; sure np

2023-12-12 22:48 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    print(cfg)
sorry for commenting this now, you're too quick!

Nit:

```suggestion
    assert container.get_exposed_port(8080)
    cfg = MetadataStoreClientConfig(host="localhost", port=8080)
```

2023-12-12 22:49 UTC, isinyaaa commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
I believe this can be fixed with a simple `rm -f` on teardown commands :)

2023-12-12 22:52 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +            print(stdout)
Nit: wouldn't this (or maybe another) order make more sense, as we're retrying after getting the error?

```suggestion
            print(e)
            print("Container logs:\n", container.get_logs())
            print("Container not ready. Retrying...")
```

2023-12-12 22:55 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +        os.system(f"rm {sqlite_db_file}") # noqa governed test
I'm a little unsure if it makes sense to repeat the `rm -f` on container teardown, as we're already doing it on the other fixture.

2023-12-12 22:55 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    sqlite_db_file = f"{model_registry_root_dir}/test/config/ml-metadata/metadata.sqlite.db"
nit: let's use path concatenation as above:

```suggestion
    sqlite_db_file = model_registry_root(request) / "test/config/ml-metadata/metadata.sqlite.db
```

2023-12-12 22:57 UTC, isinyaaa commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
I think this is fine, it was just a suggestion. Thanks for pointing out ryuk, I didn't know about it before :).

2023-12-12 23:01 UTC, isinyaaa commented on clients/python/pyproject.toml
> +testcontainers = "^3.7.1"
oh btw, a minor consideration is that I found `testcontainers-py` docs really terse.

2023-12-13 09:12 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    print(cfg)
Sorry, I do not think this is right.
The exposed port 8080 gets mapped to a bindable port on the system running the Testcontainer.
So your proposed line 40 would not work?
Am I missing something?

2023-12-13 09:15 UTC, tarilabs commented on clients/python/tests/conftest.py
> +        os.system(f"rm {sqlite_db_file}") # noqa governed test
I felt it didn't hurt being declarative about session cleanup.

2023-12-13 09:37 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
Here is output on my end _with_ and without `-s`:
![image](https://github.com/opendatahub-io/model-registry/assets/1699252/d832c7b6-3d37-4883-aa8f-da153a3f420f)

2023-12-13 09:45 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
should be sovled by https://github.com/opendatahub-io/model-registry/pull/225/commits/de399a8fe7a534cfa22aca1259ea550d4334d897

2023-12-13 09:53 UTC, lampajr approved these changes, later dismissed
Looks great to me.

Tests are working locally with both `pytest` and `pytest -x -s` commands, furthermore using all possible ml-metadata binaries (`ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }` and `{ url = "https://github.com/tarilabs/ml-metadata-remote/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }`).

2023-12-13 13:55 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +    print(cfg)
oh you're right, sorry I misunderstood what you had done here. Resolving...

2023-12-13 13:57 UTC, isinyaaa commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
Some tests don't need the fixture, so they'll print needless errors when autousing it. Wouldn't it make more sense to include this fixture only where we are using plain_wrapper?

<img width="1277" alt="image" src="https://github.com/opendatahub-io/model-registry/assets/39812919/05f7fc56-4779-44d9-87c9-0d1d5c484003">

2023-12-13 14:28 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
I haven't found a way to include conditionally the fixture only when `plain_wrapper` is used by other tests.

I'd suggest if we have a quick solution, great let's implement it; otherwise, this message is only displayed with verbose output, is not making any failures, and this PR in the bigger picture solves to avoid depending on a capability of MLMD which is arch specific (and that we don't use "in prod") and aligns with Go core test strategy (using Testcontainers).

2023-12-13 21:29 UTC, isinyaaa commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
I made an experiment to demonstrate that it's possible, check it out here: https://github.com/isinyaaa/model-registry/commit/f3d9e6de3a871243ac806537c3ff522f6666fd16

2023-12-13 23:01 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
@isinyaaa looking at the linked change, makes sense to me.
Separation of concerns, the session-scoped fixture raises the Testcontainer for the MLMD docker container, but provides the connection (not the plain wrapper).

You then have:
```python
plain_wrapper(mlmd_conn: MetadataStoreClientConfig, _clean_db) 
```

which is at each-test scope.

In principle I can see your proposal working; but at that point, wouldn't it make more sense _not_ having the separate `_clean_db` fixture, and just make the finalizer inside the `plain_wrapper` fixture? 🤔 

ie, move the finalizer of _clean_db inside of plain_wrapper.
At this point fixture plain_wrapper produces the MLMDStore as a result,
but also have the finalizer which erases the SQLite file.

Hope I was able to explain myself?

2023-12-14 08:28 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
@isinyaaa should be done with ef976e4

2023-12-14 13:31 UTC, isinyaaa commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
that was a nice suggestion Matteo :) I was kinda tired when I proposed that, thanks a lot for putting some thought into!

2023-12-14 13:32 UTC, isinyaaa approved these changes
LGTM!

2023-12-14 14:00 UTC, lampajr approved these changes

2023-12-14 22:11 UTC, tarilabs commented on clients/python/pyproject.toml
> +# ml-metadata = { url = "https://github.com/tarilabs/ml-metadata/releases/download/1.14.0/ml_metadata-1.14.0-py3-none-any.whl" }
> that was a nice suggestion @tarilabs :)

Teamwork ftw  💪 🚀

2023-12-15 09:05 UTC, merged