robot: fix Python client import
opendatahub-io/model-registry-bf4-kf pull request #240
Opened 2023-12-12 23:33 UTC by isinyaaa

This fixes Robot tests for the Python client.

## Description
This fixes the imported python client on Robot tests to match what's exposed after adding a higher-level API.

## How Has This Been Tested?
Hasn't been.

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-12-12 23:42 UTC, isinyaaa commented
@tarilabs I haven't been able to run this locally per the instructions you gave me:

```sh
docker run -p 9090:8080 --env METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb --volume../test/bdd:/tmp/shared gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
```

then
```sh
make build
./model-registry proxy
```

then
```sh
TEST_MODE=Python robot test
```

Am I doing something wrong? Is there a better way to run this?
From what I've noticed this fails because the MLMD types haven't been created, if so, I might be missing some step of the setup.

2023-12-13 09:06 UTC, tarilabs commented
> Am I doing something wrong? Is there a better way to run this?
> From what I've noticed this fails because the MLMD types haven't been created

When the proxy connects, it automatically creates the MLMD _type(s).
Do you get in the proxy the log line which shows successfull connection to MLMD gRPC?
If you connect to the SQLite db file, do you see the entries?

2023-12-13 10:37 UTC, lampajr approved these changes
@isinyaaa I think the issue is in your volume, you are passing `/test/bdd` but you should pass the local dir where `conn_config.pb` is stored which is `test/config/ml-metadata/`, let's try with this change and it should work.

I tried locally and `robot` tests are working properly, therefore LGTM!!

2023-12-13 10:41 UTC, lampajr commented
> I tried locally and `robot` tests are working properly, therefore LGTM!!

Nevermind, I did not use the proper binary.. they are not working running: `TEST_MODE=python robot test/robot`

2023-12-13 12:37 UTC, lampajr requested changes
This should fix an issue, still checking the other one

2023-12-13 12:37 UTC, lampajr commented on test/robot/ModelRegistry.py
>          p = ModelVersion(ModelArtifact("", ""), "", "")
```suggestion
        p = ModelVersion("", "", "")
```

2023-12-13 12:45 UTC, lampajr commented on test/robot/ModelRegistry.py
>          p = ModelVersion(ModelArtifact("", ""), "", "")
Ok I think this is enough to fix all issues, the other errors are related to unimplemented keywords in `MRkeywords` that I think can be implemented in a separated PR

2023-12-13 13:59 UTC, isinyaaa commented on test/robot/ModelRegistry.py
>          p = ModelVersion(ModelArtifact("", ""), "", "")
thanks, Andrea :) I'm still not too familiar with the framework. Will apply this later :)

2023-12-13 14:00 UTC, lampajr commented on test/robot/ModelRegistry.py
>          p = ModelVersion(ModelArtifact("", ""), "", "")
No worries, me neither hehe

2023-12-13 14:10 UTC, lampajr approved these changes
LGTM, robot tests are working for me

2023-12-13 17:55 UTC, tarilabs approved these changes
Looks good with me.

Made sure to have installed: `pip install robotframework robotframework-requests PyYAML`
and of course all python MR client dep and related.

Tested locally with.

In one terminal
```
docker run -p 9090:8080 --env METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb --volume ./test/config/ml-metadata:/tmp/shared gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
```

In another terminal
```
./model-registry proxy
I1213 18:35:25.649365   14668 proxy.go:31] proxy server started at localhost:8080
I1213 18:35:25.649665   14668 proxy.go:37] connecting to MLMD server localhost:9090..
I1213 18:35:25.678205   14668 proxy.go:49] connected to MLMD server
```

In a third terminal:
```
robot UserStory.robot
TEST_MODE=Python robot MRandLogicalModel.robot
robot MRandLogicalModel.robot
```

![image](https://github.com/opendatahub-io/model-registry/assets/1699252/5d7b48f7-1b2c-4245-9ea0-994f247085e0)

2023-12-13 20:35 UTC, merged

2023-12-13 20:36 UTC, isinyaaa commented
thanks a lot for the instructions, Matteo :) I managed to run it as well

2023-12-13 22:51 UTC, tarilabs commented
> thanks a lot for the instructions, Matteo :) I managed to run it as well

Always glad to help @isinyaaa , teamwork to the moon 🚀 🌙