Implement gRPC GetArtifactType
opendatahub-io/model-registry-bf4-kf pull request #26
Opened 2023-09-25 06:50 UTC by tarilabs

resolves #25 

## Description
Implement gRPC `GetArtifactType`

## How Has This Been Tested?
in one terminal:

```
make build
make run/server
```

in another terminal:

```
python test/python/test_mlmetadata.py 
```

then running the following python script:

```python
from grpc import insecure_channel
from ml_metadata.proto import metadata_store_service_pb2
from ml_metadata.proto import metadata_store_service_pb2_grpc

def main():
    channel = insecure_channel('localhost:8080')
    store = metadata_store_service_pb2_grpc.MetadataStoreServiceStub(channel)

    request = metadata_store_service_pb2.GetArtifactTypeRequest()
    request.type_name = "SavedModel"

    response = store.GetArtifactType(request)
    print(response)

if __name__ == '__main__':
    main()
```

Outputs as expected:

```
$ python test/python/test_getartifacttype.py 
artifact_type {
  id: 2
  name: "SavedModel"
}
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-09-25 06:52 UTC, tarilabs commented on internal/server/grpc_server.go
> +	defer handleTransaction(ctx, &err)
I preferred to take "same approach" and place this on a tx context too, even if this is only a read, for consistency.

2023-09-25 15:05 UTC, dhirajsb requested changes
Please add the test client code to the current prototype integration test `test/python/test_mlmetadata.py` script. We can re-use it in a later testframework.

2023-09-25 16:29 UTC, lampajr approved these changes, later dismissed

2023-09-26 07:36 UTC, lampajr approved these changes

2023-09-26 15:09 UTC, dhirajsb approved these changes
:+1:

2023-09-26 20:09 UTC, isinyaaa approved these changes
lgtm!

2023-09-27 09:51 UTC, tarilabs commented
no vetos, no missing, all approval; proceeding to merge.

2023-09-27 09:51 UTC, merged