Py: Add support for importing models from Hugging Face Hub
opendatahub-io/model-registry-bf4-kf pull request #260
Opened 2024-01-03 22:42 UTC by isinyaaa

Related: #133

## Description

Fixes docstrings and some type errors, also simplifies type checking in `ProtoBase.unmap` and `MLMDStore.get_type_id`.

As laid out in https://github.com/opendatahub-io/model-registry/issues/133#issuecomment-1861912870, the API provides
utility calls to fetch metadata from a given Hub repo automatically.

The following metadata is fetched:
- In the absence of a user-provided description, the repo's `README.md` will be used.
- The [model card](https://huggingface.co/docs/hub/model-cards) tags.
- Additional model card metadata.

TODO:
- [ ] Large `README.md` fail to upload on a deployed cluster
- [ ] List can't be imported as metadata

## How Has This Been Tested?

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-01-04 08:40 UTC, tarilabs approved these changes, later dismissed
Thank you!

I'm good with merging this early and adapting for `storageUri` if needed (more below) in subsequent PRs too.

2024-01-04 08:40 UTC, tarilabs commented on clients/python/src/model_registry/_client.py
> +            ),
@lampajr as we're storing the "raw binary URL" when import from HF, I believe we will need to make sure in MC reconciliation we're not using Secret/S3 but the `storageURI` similar to:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: example
    serving.kserve.io/deploymentMode: ModelMesh
  name: example
  namespace: ds-mre2e
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      name: ''
      resources: {}
      runtime: mmserver1
      storageUri: https://github.com/tarilabs/demo20231212/blob/main/v1.nb20231206162408/mnist.onnx?raw=true
```

(this example demonstrates using binary from GitHub, but analogously using the raw binary URI from HF as highlighted.

Wdyt?

2024-01-04 08:40 UTC, tarilabs commented on clients/python/tests/test_client.py
> +    assert (ma := mr_api.get_model_artifact_by_params(mv.id))
Looking in Python 3 mailing-list seems to me using the walrus in this way is a bit controversial... that said, I'm totally fine if we believe it makes the test more robust at the expense of readability of where the variable scope belongs.

2024-01-04 11:53 UTC, lampajr commented on clients/python/src/model_registry/_client.py
> +            ),
+1 if we have different ways to create IS based on the nature of the model (either "internal" using s3 and the data connection or "external" using the storageUri).

Instead, if we decide to go with https://github.com/opendatahub-io/model-registry/issues/254 we will have a standardized way to create IS using `storageUri` only, this way we don't have to create different IS based on the model nature but just use the single model-registry specific way.

2024-01-04 12:20 UTC, isinyaaa commented
I'd like your opinion on the metadata imports, specifically in regards to `list`s. We have two options right now:
1. Support that in a non-standard way (e.g. what was proposed on [hf POC](https://github.com/isinyaaa/hf-mlmd-mapping-poc/blob/main/main.py#L107)).
2. Discard all list metadata except for `tags` which we know how to deal with.

2024-01-04 12:22 UTC, isinyaaa commented
Also, as discussed previously, regarding the upload limits on deployed clusters, do you think it'd be better to crop large `README.md` files to some character limit or simply don't use it?

2024-01-04 12:26 UTC, isinyaaa commented on clients/python/tests/test_client.py
> +    assert (ma := mr_api.get_model_artifact_by_params(mv.id))
GPT suggests something like:

```py
    client_model_version = mr_client.get_model_version(name, version)
    assert model_version.id == client_model_version.id
    client_model_artifact = mr_client.get_model_artifact(name, version)
    assert model_artifact.id == client_model_artifact.id
```

would you prefer that? IMO it's not a big difference, except for the variable names, but we can surely avoid assignment expressions on assertions.

2024-01-04 12:52 UTC, antisaling commented
Changes in v2:
- `huggingface-hub` is now properly marked as an optional dependency
- Related tests are skipped if the dependency is not available

Edit: updated the README.md to add install instructions for the extra group.

2024-01-04 12:55 UTC, tarilabs commented on clients/python/tests/test_client.py
> +    assert (ma := mr_api.get_model_artifact_by_params(mv.id))
maybe I haven't expressed myself correctly.

To me, doing:

```python
_mv = mr_client.get_model_version(name, version)
assert mv.id == _mv.id
```
or 

```python
temp1 = mr_client.get_model_version(name, version)
assert mv.id == temp1.id
```

is clearer than doing the walrus op inside of assert with:

```python
assert( temp1 := mr_client.get_model_version(name, version) )
assert mv.id == temp1.id
```

Simply because in the first two variants, you have the usual, natural view on the scope for `_mv` or `temp1`, while seems is a bit more tricky to follow what is the scope of `temp1` if it's walrus `:=` -defined inside the assert parameter call?

The naming of the variable is fine either way, using `_` prefix, you could also call it `mv_result` to differentiate from `mv` being the "original" one under test, etc. I have really no preference over variable naming here, I just wanted to highlight about my understanding of `:=` and I wanted to hear your thoughts? Does its usage bring some advantages which might have missed?

2024-01-04 12:57 UTC, isinyaaa commented
Should we test extras on the default CI jobs or add new ones? @tonyxrmdavidson @rkubis

2024-01-04 12:58 UTC, tarilabs commented
> I'd like your opinion on the metadata imports, specifically in regards to `list`s. We have two options right now:
> 
> 1. Support that in a non-standard way (e.g. what was proposed on [hf POC](https://github.com/isinyaaa/hf-mlmd-mapping-poc/blob/main/main.py#L107)).
> 2. Discard all list metadata except for `tags` which we know how to deal with.

I believe we need to decide about this more in general since we'll be asked from UI team how to store lists as custom_property, and I recall there is some limitations in the tradeoff between what allowed by MLMD and what possible as k8s resources. To be determined.

> Also, as discussed previously, regarding the upload limits on deployed clusters, do you think it'd be better to crop large `README.md` files to some character limit or simply don't use it?

Did we confirm where the gRPC limit is coming from? 🤔 is this an hard-coded limit in MLMD server?

2024-01-04 14:07 UTC, lampajr requested changes
Overall looks good to me, left a change request as I think it could break the functionality

2024-01-04 14:07 UTC, lampajr commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
I fear this could break the model version registration as we do not have any `tags` property in MLMD [1] and based on my understanding we decided to leave those tags/labels as `custom properties` rather than `properties`, see https://github.com/opendatahub-io/model-registry/issues/151. Am I right?

[1] https://github.com/opendatahub-io/model-registry/blob/53b744622382220d7fd827f52ba74f4d99b0319b/pkg/core/core.go#L65-L69

2024-01-04 14:11 UTC, lampajr commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
In fact tests are working just because you are setting the `ModelVersion` type with `tags` property https://github.com/opendatahub-io/model-registry/blob/53b744622382220d7fd827f52ba74f4d99b0319b/clients/python/tests/conftest.py#L105-L114

2024-01-04 14:25 UTC, isinyaaa commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
Nice catch! I will update the tags field to be a `custom_property`.

2024-01-04 14:28 UTC, isinyaaa commented
> > I'd like your opinion on the metadata imports, specifically in regards to `list`s. We have two options right now:
> > 
> > 1. Support that in a non-standard way (e.g. what was proposed on [hf POC](https://github.com/isinyaaa/hf-mlmd-mapping-poc/blob/main/main.py#L107)).
> > 2. Discard all list metadata except for `tags` which we know how to deal with.
> 
> I believe we need to decide about this more in general since we'll be asked from UI team how to store lists as custom_property, and I recall there is some limitations in the tradeoff between what allowed by MLMD and what possible as k8s resources. To be determined.

I'll assume it's safer to discard those for now then. As for the tags, can we keep the current format or should we drop it as well?

> > Also, as discussed previously, regarding the upload limits on deployed clusters, do you think it'd be better to crop large `README.md` files to some character limit or simply don't use it?
> 
> Did we confirm where the gRPC limit is coming from? 🤔 is this an hard-coded limit in MLMD server?

Unfortunately, just looking at the source code, it's only apparent that it's an absl warning from the server, but I wasn't able to find where it's being thrown.

For future reference, the error we get for e.g. `aident-ai/bge-base-en-onnx` is:

```raw
ResourceExhaustedError: received metadata size exceeds hard limit (value length 29943 vs. 16384)
```

From the [gRPC status code reference](https://grpc.github.io/grpc/python/_modules/grpc.html#StatusCode) this means that "Some resource has been exhausted, perhaps a per-user quota, or perhaps the entire file system is out of space." which isn't too clear still.

I'm investigating whether it's possible to override some connection parameter (as per this [SO answer](https://stackoverflow.com/a/56768255)) to make that work, but I'm confused as to why local tests don't raise this.

2024-01-04 15:31 UTC, isinyaaa commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
Are we going to be using a struct field for those properties as @tarilabs showed on https://github.com/opendatahub-io/model-registry/issues/151#issuecomment-1814004316 ? Also, should those be called `tags` or `labels`?

2024-01-05 08:55 UTC, lampajr commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
Well IMO I would completely remove the `tags` field from the model version itself and let users decide whether store them as custom properties or not, I mean custom properties are free properties that user can add or not.

IIUC this is exactly the intention of Dhiraj comment on https://github.com/opendatahub-io/model-registry/issues/151#issuecomment-1813025542

2024-01-05 09:36 UTC, tarilabs commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
Until we have an uniform example confirmed from UI pov on how they want to store labels/tags/etc which will pop up in the UI, I concur with Andrea's https://github.com/opendatahub-io/model-registry/pull/260#discussion_r1442633066 you could consider avoiding _storing_ it.

That said, once UI starts to be developed, tags/labels will have an opinionated representation in the UI; when that happens, I think it will be meaningful that any tags/labels in a HF card, is automatically mapped to the same custom property--without the user having to repeat it manually during the HF-import.

wdyt?

2024-01-05 09:44 UTC, lampajr commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
+1 I agree on automatically mapping them as custom properties while importing from external sources like for HF

So at the end we would not have any `tags` field in the api, (I) if users perform custom/manual registration then they can decide to store or not labels as custom properties (UI will automatically manage this); (II) if user imports from HF, the python client will automatically create `tags`/`labels` as custom properties following the same approach that the UI will use (for now we can decide our own and update that at later step).

Did I understood correctly?

2024-01-05 12:17 UTC, isinyaaa commented on clients/python/src/model_registry/types/contexts.py
> +            "tags": ",".join(self.tags),
Oh right, now I got it, thanks for the clarification :)

2024-01-05 12:44 UTC, isinyaaa commented on clients/python/tests/test_client.py
> +    assert (ma := mr_api.get_model_artifact_by_params(mv.id))
Not at all, Matteo, but notice that the parens around the expression are not part of the assert call, but are only there so that we can enclose the assignment expression statement, and then assert its result is not `None` (as the `assert` won't create a new scope, the scope of the variable is the same as without the assertion).

I'll update the code to be more expressive as you wish, but we still have to `assert temp1 is not None` to avoid pyright warnings, as the `get_*` functions might return `None` on the absence of an object on the store.

2024-01-05 13:53 UTC, tarilabs commented on clients/python/tests/test_client.py
> +    assert (ma := mr_api.get_model_artifact_by_params(mv.id))
thank you for taking the time offline. As mentioned, that helped me to pin-down it was a misunderstanding of scoping rules in python on my end.

We can resolve this comment with no further change of code to be considered.

2024-01-08 10:10 UTC, tarilabs commented
> I'm investigating whether it's possible to override some connection parameter (as per this [SO answer](https://stackoverflow.com/a/56768255)) to make that work, but I'm confused as to why local tests don't raise this.

So far, I was only able to get a different error:

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "PostgreSQL metadata source error: ERROR:  index row requires 20888 bytes, maximum size is 8191
"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-08T10:07:45.075406312+00:00", grpc_status:13, grpc_message:"PostgreSQL metadata source error: ERROR:  index row requires 20888 bytes, maximum size is 8191\n"}"
>
```

edit: can be replicated beyond MR python client using REST with:

<details>

```
curl -X 'POST' \
  'https://mr-secure-ds-mre2e.apps.rosa.mmortari-rosa-h.w0x4.p3.openshiftapps.com/api/model_registry/v1alpha1/registered_models' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "---\r\ntags:\r\n- sentence-transformers\r\n- feature-extraction\r\n- sentence-similarity\r\n- transformers\r\n- mteb\r\nlicense: mit\r\nlanguage:\r\n- en\r\n---\r\n\r\n\r\nThis is a fork from [BAAI\/bge-base-en-v1.5](https:\/\/huggingface.co\/BAAI\/bge-base-en-v1.5) and exported to onnx for inference.\r\n\r\n=======\r\n\r\n\r\n<h1 align=\"center\">FlagEmbedding<\/h1>\r\n\r\n\r\n<h4 align=\"center\">\r\n    <p>\r\n        <a href=#model-list>Model List<\/a> | \r\n        <a href=#frequently-asked-questions>FAQ<\/a> |\r\n        <a href=#usage>Usage<\/a>  |\r\n        <a href=\"#evaluation\">Evaluation<\/a> |\r\n        <a href=\"#train\">Train<\/a> |\r\n        <a href=\"#contact\">Contact<\/a> |\r\n        <a href=\"#citation\">Citation<\/a> |\r\n        <a href=\"#license\">License<\/a> \r\n    <p>\r\n<\/h4>\r\n\r\nMore details please refer to our Github: [FlagEmbedding](https:\/\/github.com\/FlagOpen\/FlagEmbedding).\r\n\r\n\r\n[English](README.md) | [\u4E2D\u6587](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/blob\/master\/README_zh.md)\r\n\r\nFlagEmbedding can map any text to a low-dimensional dense vector which can be used for tasks like retrieval, classification,  clustering, or semantic search.\r\nAnd it also can be used in vector databases for LLMs.\r\n\r\n************* \uD83C\uDF1F**Updates**\uD83C\uDF1F *************\r\n- 09\/15\/2023: Release [paper](https:\/\/arxiv.org\/pdf\/2309.07597.pdf) and [dataset](https:\/\/data.baai.ac.cn\/details\/BAAI-MTP).\r\n- 09\/12\/2023: New Release: \r\n    - **New reranker model**: release cross-encoder models `BAAI\/bge-reranker-base` and `BAAI\/bge-reranker-large`, which are more powerful than embedding model. We recommend to use\/fine-tune them to re-rank top-k documents returned by embedding models. \r\n    - **update embedding model**: release `bge-*-v1.5` embedding model to alleviate the issue of the similarity distribution, and enhance its retrieval ability without instruction.\r\n- 09\/07\/2023: Update [fine-tune code](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/blob\/master\/FlagEmbedding\/baai_general_embedding\/README.md): Add script to mine hard negatives and support adding instruction during fine-tuning.\r\n- 08\/09\/2023: BGE Models are integrated into **Langchain**, you can use it like [this](#using-langchain); C-MTEB **leaderboard** is [available](https:\/\/huggingface.co\/spaces\/mteb\/leaderboard).  \r\n- 08\/05\/2023: Release base-scale and small-scale models, **best performance among the models of the same size \uD83E\uDD17**\r\n- 08\/02\/2023: Release `bge-large-*`(short for BAAI General Embedding) Models, **rank 1st on MTEB and C-MTEB benchmark!** :tada: :tada: \r\n- 08\/01\/2023: We release the [Chinese Massive Text Embedding Benchmark](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/blob\/master\/C_MTEB) (**C-MTEB**), consisting of 31 test dataset.   \r\n\r\n\r\n## Model List\r\n\r\n`bge` is short for `BAAI general embedding`.\r\n\r\n|              Model              | Language | | Description | query instruction for retrieval\\* |\r\n|:-------------------------------|:--------:| :--------:| :--------:|:--------:|\r\n|  [BAAI\/bge-reranker-large](https:\/\/huggingface.co\/BAAI\/bge-reranker-large) |   Chinese and English | [Inference](#usage-for-reranker) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/reranker) | a cross-encoder model which is more accurate but less efficient \\** |   |\r\n|  [BAAI\/bge-reranker-base](https:\/\/huggingface.co\/BAAI\/bge-reranker-base) |   Chinese and English | [Inference](#usage-for-reranker) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/reranker) | a cross-encoder model which is more accurate but less efficient \\** |   |\r\n|  [BAAI\/bge-large-en-v1.5](https:\/\/huggingface.co\/BAAI\/bge-large-en-v1.5) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution | `Represent this sentence for searching relevant passages: `  |\r\n|  [BAAI\/bge-base-en-v1.5](https:\/\/huggingface.co\/BAAI\/bge-base-en-v1.5) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution | `Represent this sentence for searching relevant passages: `  |\r\n|  [BAAI\/bge-small-en-v1.5](https:\/\/huggingface.co\/BAAI\/bge-small-en-v1.5) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution  | `Represent this sentence for searching relevant passages: `  |\r\n|  [BAAI\/bge-large-zh-v1.5](https:\/\/huggingface.co\/BAAI\/bge-large-zh-v1.5) |   Chinese | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution | `\u4E3A\u8FD9\u4E2A\u53E5\u5B50\u751F\u6210\u8868\u793A\u4EE5\u7528\u4E8E\u68C0\u7D22\u76F8\u5173\u6587\u7AE0\uFF1A`  |\r\n|  [BAAI\/bge-base-zh-v1.5](https:\/\/huggingface.co\/BAAI\/bge-base-zh-v1.5) |   Chinese |  [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution | `\u4E3A\u8FD9\u4E2A\u53E5\u5B50\u751F\u6210\u8868\u793A\u4EE5\u7528\u4E8E\u68C0\u7D22\u76F8\u5173\u6587\u7AE0\uFF1A`  |\r\n|  [BAAI\/bge-small-zh-v1.5](https:\/\/huggingface.co\/BAAI\/bge-small-zh-v1.5) |   Chinese | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | version 1.5 with more reasonable similarity distribution | `\u4E3A\u8FD9\u4E2A\u53E5\u5B50\u751F\u6210\u8868\u793A\u4EE5\u7528\u4E8E\u68C0\u7D22\u76F8\u5173\u6587\u7AE0\uFF1A`  |\r\n|  [BAAI\/bge-large-en](https:\/\/huggingface.co\/BAAI\/bge-large-en) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | :trophy: rank **1st** in [MTEB](https:\/\/huggingface.co\/spaces\/mteb\/leaderboard) leaderboard | `Represent this sentence for searching relevant passages: `  |\r\n|  [BAAI\/bge-base-en](https:\/\/huggingface.co\/BAAI\/bge-base-en) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/github.com\/FlagOpen\/FlagEmbedding\/tree\/master\/examples\/finetune) | a base-scale model but with similar ability to `bge-large-en` | `Represent this sentence for searching relevant passages: `  |\r\n|  [BAAI\/bge-small-en](https:\/\/huggingface.co\/BAAI\/bge-small-en) |   English | [Inference](#usage-for-embedding-model) [Fine-tune](https:\/\/ [...]

2024-01-09 23:45 UTC, isinyaaa commented
Importing the `README.md` file as a field won't really be possible due to limitations on the MLMD server, but I'd argue that it makes sense to pursue the idea of having it as a separate `Artifact`, as discussed with @tarilabs @lampajr @rareddy . However, what artifact type should that be? Moreover, where should we store that data?

2024-01-10 09:15 UTC, tarilabs commented
> Importing the `README.md` file as a field won't really be possible due to limitations on the MLMD server, but I'd argue that it makes sense to pursue the idea of having it as a separate `Artifact`, as discussed with @tarilabs @lampajr @rareddy . However, what artifact type should that be? Moreover, where should we store that data?

I'd recommend to _default_ `description` to the first arbitrary-length characters (say 100? followed by ellipsis ` (...)`) so the end-user can also always override this default if need be during HR import.

For the `DocArtifact` I agree with Dhiraj is likely another type of artifact, but we need to sync that choice on all ends (backend, REST, and Python) and I would recommend capturing that in a following JIRA/PR.
wdyt?

2024-01-11 14:51 UTC, isinyaaa commented
> > Importing the `README.md` file as a field won't really be possible due to limitations on the MLMD server, but I'd argue that it makes sense to pursue the idea of having it as a separate `Artifact`, as discussed with @tarilabs @lampajr @rareddy . However, what artifact type should that be? Moreover, where should we store that data?
> 
> I'd recommend to _default_ `description` to the first arbitrary-length characters (say 100? followed by ellipsis ` (...)`) so the end-user can also always override this default if need be during HF import.

This can be left for later, as discussed privately, due to the additional complexity.

> For the `DocArtifact` I agree with Dhiraj is likely another type of artifact, but we need to sync that choice on all ends (backend, REST, and Python) and I would recommend capturing that in a following JIRA/PR. wdyt?

Documented on #263.

2024-01-11 15:15 UTC, dtrifiro commented on clients/python/src/model_registry/_client.py
> +        model_author = model_info.author or "huggingface"
Could this create issues in some cases?

For example, https://huggingface.co/distilbert-base-cased has no namespace but be found from the huggingface namespace (https://huggingface.co/huggingface), while other repos are actually namespaced 

https://huggingface.co/huggingface/falcon-40b-gptq

2024-01-11 15:19 UTC, dtrifiro approved these changes

2024-01-15 15:49 UTC, antisaling commented on clients/python/src/model_registry/_client.py
> +        model_author = model_info.author or "huggingface"
I'll insert a warning here then, we default it to "unknown".

2024-01-15 15:55 UTC, isinyaaa commented
How should we deal with versions? I'm thinking about users that want to update a model after the initial import, so we probably could default the version to be the latest commit ID. wdyt?

2024-01-15 16:35 UTC, dhirajsb commented
The user should provide version labels explicitly. Commit IDs should not be used for version labels, since model version labels are more like Docker image labels. And a registered model version is more like a Docker image release. 
Keep in mind that we are not considering experiments and runs yet, for which commit ids would be more suitable as run labels.

2024-01-16 12:04 UTC, dtrifiro commented on clients/python/src/model_registry/_client.py
> +        model_author = model_info.author or "huggingface"
https://huggingface.co/Unknown ?

2024-01-17 08:44 UTC, lampajr approved these changes

2024-01-17 18:20 UTC, merged

2024-01-17 18:22 UTC, tarilabs approved these changes
tested latest using https://huggingface.co/tarilabs/mnist/tree/v1.nb20231206162408

![image](https://github.com/opendatahub-io/model-registry/assets/1699252/7de6a516-ef2a-43c5-b5de-29adb0d720e6)

and result indexed on MR:

![image](https://github.com/opendatahub-io/model-registry/assets/1699252/6454ff36-2c0e-4360-9a9e-c11af862ca39)

registered_model:

```
curl --silent -X 'GET' \
  "$MR_HOSTNAME/api/model_registry/v1alpha1/registered_models?pageSize=100&orderBy=ID&sortOrder=DESC&nextPageToken=" \
  -H 'accept: application/json' | jq .items
[
  {
    "createTimeSinceEpoch": "1705514870832",
    "customProperties": {},
    "id": "37",
    "lastUpdateTimeSinceEpoch": "1705514870832",
    "name": "tarilabs-mnist-from-hf",
    "state": "LIVE"
  },
...
```

model_version:

```
curl --silent -X 'GET' \
  "$MR_HOSTNAME/api/model_registry/v1alpha1/registered_models/37/versions?pageSize=100&orderBy=ID&sortOrder=DESC&nextPageToken=" \
  -H 'accept: application/json' | jq .items
[
  {
    "author": "tarilabs",
    "createTimeSinceEpoch": "1705514871435",
    "customProperties": {
      "license": {
        "string_value": "apache-2.0"
      },
      "model_author": {
        "string_value": "tarilabs"
      },
      "model_origin": {
        "string_value": "huggingface_hub"
      },
      "repo": {
        "string_value": "tarilabs/mnist"
      },
      "source_uri": {
        "string_value": "https://huggingface.co/tarilabs/mnist/resolve/main/mnist.onnx"
      }
    },
    "description": "testing out PR 260",
    "id": "38",
    "lastUpdateTimeSinceEpoch": "1705514871435",
    "name": "v1.nb20231206162408",
    "state": "LIVE"
  }
]
```

model_artifact:

```
curl --silent -X 'GET' \
  "$MR_HOSTNAME/api/model_registry/v1alpha1/model_versions/38/artifacts" \
  -H 'accept: application/json' | jq .items
[
  {
    "artifactType": "model-artifact",
    "createTimeSinceEpoch": "1705514872127",
    "customProperties": {},
    "id": "7",
    "lastUpdateTimeSinceEpoch": "1705514872127",
    "modelFormatName": "onnx",
    "modelFormatVersion": "1",
    "name": "tarilabs-mnist-from-hf",
    "state": "UNKNOWN",
    "storagePath": "mnist.onnx",
    "uri": "https://huggingface.co/tarilabs/mnist/resolve/main/mnist.onnx"
  }
]
```

@lampajr does it match your expectations on entity attributes? Seems to me it's coherent/as expected.

2024-01-17 18:28 UTC, lampajr commented
> @lampajr does it match your expectations on entity attributes? Seems to me it's coherent/as expected.
+1 it seems coherent to me too, everything is properly populated (worth to note that `storageKey` in modelArtifact is correctly nil as we are referencing external model)