update to python/client README to give commands for running python te…
opendatahub-io/model-registry-bf4-kf pull request #272
Opened 2024-01-24 16:23 UTC by tonyxrmdavidson

Update to give clear intstructions on how to run tests on a mac m2 machine

2024-01-25 08:19 UTC, tarilabs commented on clients/python/README.md
> +```
I would prefer to guide Dev users to alternatives provided in TOML file already:

https://github.com/opendatahub-io/model-registry/blob/0497cf4b325e509e8adabaf45f3fbf3864858d80/clients/python/pyproject.toml#L13-L16

and instruct them to select alternatives by uncommenting/commenting.

Currently working to migrate some of those releases to ODH org at least.

2024-01-26 19:20 UTC, isinyaaa commented on clients/python/README.md
> +If you want run tests locally you will need to set up a colima develeopment environment using the instructions [here](https://github.com/opendatahub-io/model-registry/blob/main/CONTRIBUTING.md#colima
Nit: typo

```suggestion
If you want run tests locally you will need to set up a colima development environment using the instructions [here](https://github.com/opendatahub-io/model-registry/blob/main/CONTRIBUTING.md#colima)
```

2024-01-26 19:23 UTC, isinyaaa commented on clients/python/README.md
> +## Running Locally on Mac M1 or M2 (arm64 architecture)
This should be a subsubsection, under _development_.

2024-01-26 19:24 UTC, isinyaaa commented on clients/python/README.md
> +*note: when you add this python whl it will update both your pyprojec.toml and poetry.lock files. **DO NOT COMMIT** these changes.*
While this is correct in some sense, I'd rather say that the user will have to change the *package source* to one compatible with ARM64, and then point them to the source.

I'd also get rid of this note, the user can do whatever they want in their forks.

2024-01-26 19:25 UTC, isinyaaa commented on clients/python/README.md
> +*note: when you add this python whl it will update both your pyprojec.toml and poetry.lock files. **DO NOT COMMIT** these changes.*
Note: if you want to leave instructions for guidance, you can put them all together in a single code block annotated as `sh`.

2024-01-26 19:26 UTC, isinyaaa commented on clients/python/README.md
> +```
Matteo, could you successfully use `nox` on the Colima/devcontainers setup? If so, that's also what I'd recommend here.

2024-01-26 19:27 UTC, isinyaaa requested changes
Requests inline.

2024-01-26 19:52 UTC, tarilabs commented on clients/python/README.md
> +```
Isn't nox used for testing matrix? 🤔 
I'm not sure I fully understood how this would solve for development environment; happy to try commands/setup, but here I'm afraid I'm not yet following

2024-01-29 12:02 UTC, tonyxrmdavidson commented on clients/python/README.md
> +```
Re tested the process and updated the PR with changes to take take account of comments here.

2024-01-29 12:03 UTC, tonyxrmdavidson commented on clients/python/README.md
> +*note: when you add this python whl it will update both your pyprojec.toml and poetry.lock files. **DO NOT COMMIT** these changes.*
Agree with comments and updated the PR with appropriate changes

2024-01-29 12:03 UTC, tonyxrmdavidson commented on clients/python/README.md
> +## Running Locally on Mac M1 or M2 (arm64 architecture)
Moved it under the development heading

2024-01-29 12:15 UTC, isinyaaa approved these changes

2024-01-29 12:58 UTC, tarilabs approved these changes

2024-02-02 14:19 UTC, merged