Add first draft of Data Access Layer, with test
opendatahub-io/model-registry-bf4-kf pull request #34
Opened 2023-09-26 13:17 UTC by tarilabs

## Description
Pair programmed with @lampajr as discussed first draft of Data Access Layer (DAL).

Key points to be discussed:

- we opted for multiple `<entity>Handler`(s) interface to leverage GoLang implicit interface on call site if ever needed
    - we considered "one giant interface" but we preferred above
- we opted during `create` method of CRUD, to explicit all properties of the entity, as from client call site only after creation you get an instance of the entity, which could be passed to Update, Delete, etc.
    - we considered passing entity also for creation method but we preferred above
    - there is some opportunity for further isolation of DAL with regards to "built-in types" (int, bool, string, struct, proto, etc) as defined by the proto, for the time being we opted to keep this in order to make it explicit (as anyway a change in the proto will need to reflect on the DAL anyway)
    - we provide convenience query method for what we believe are most common needed

Open points:
- where to place logic for attributes, for example unique version for an artifactType: gorm or DB constraint/key ?
- semantic of `Create` in CRUD: keep currently existing Create-or-Update-if-already-exising or switch to Create-or-Error-if-already-existing ?

## How Has This Been Tested?
```
go test -timeout 30s ./...
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-09-26 13:46 UTC, lampajr submitted a review, later dismissed

2023-09-26 15:02 UTC, rareddy commented on internal/service/db_service.go
> +		properties map[string]proto.PropertyType) (result *db.Type, err error)
- This call is always behind the gRPC call, IMO we should always use `db.ArtifactType` as the input nd not have individual properties defined. The converters for each type are being generated where gRPC -> DB.
- Since we are defining the database layer, how about using methods corresponding to its lingo like `insert`, `read`, `update`, and `delete`.  Can also have an `upsert` which is `insert` when no record found otherwise a `update`?
- Since we are saying individual interface for each table, can we drop the verbose `Artifact` in the method names?

2023-09-26 15:02 UTC, rareddy commented on internal/service/db_service.go
> +type ArtifactHandler interface {
One interface per `go` file?

2023-09-26 16:33 UTC, dhirajsb requested changes
Added comments for required changes.

2023-09-26 16:33 UTC, dhirajsb commented on internal/service/db_service.go
> +type ArtifactTypeHandler interface {
Create a single interface called DBService with Create/Update functions for all schema tables.

2023-09-26 16:33 UTC, dhirajsb commented on internal/service/db_service.go
> +type Handle struct {
Move the implementation into another file `db_service_handler.go`.

2023-09-26 16:33 UTC, dhirajsb commented on internal/service/db_service.go
> +	CreateArtifactType(name string, version *string) (result *db.Type, err error)
All DBService funcs should take db.* structs as parameters. Since that's the output of the gRPC to DB Converters. 
That will allow us to work with not only all the fields in that type, but since we have relationships in them, the `DBServiceHandler` can also use Gorm [associations](https://gorm.io/docs/associations.html) to automatically create/update `Properties` (MUST be done) and other relationships like `attributions` and `associations`. 
There are some APIs in the gRPC interface where multiple objects are created in a single call (A `Context` with all it's `Artifacts` and `Executions`). So the DBService needs to be able to support that as well. Gorm associations will make that easy to do. Just need to check for the presence of the relationship field, and make sure foreign keys are correctly set before saving the association. There is also a `FullSaveAssociation` option which can save an entire tree of objects.

2023-09-26 16:33 UTC, dhirajsb commented on internal/service/db_service.go
> +		properties map[string]proto.PropertyType) (result *db.Type, err error)
Create a single interface for all types called `DBService`, otherwise we will have a clutter of DB interfaces and handlers to deal with. 
The implementation can still be split into multiple handlers using anonymous fields like so:
```go
// make sure handler implements all interface operations
var _ DBService = dbServiceHandler{}
var _ DBService = (*dbServiceHandler)(nil)

func NewDBService() DBService {
  return &dbServiceHandler{}
}

struct dbServiceHandler {
  artifactHandler
  contextHandler
  ...
}
```
Then split out `*Handler structs` into `*_handler.go`. This way the service user just needs to know about `DBService` and `NewDBService`, which are the only types exported. 
If the individual handlers need to call other handlers (to handle associations), then they could have a DBService field, which could be initialized to `*dbServiceHandler` in `NewDBService`.

2023-09-26 17:24 UTC, dhirajsb commented on internal/service/db_service.go
> +	GetArtifactTypes(id *int64, name *string, version *string) ([]db.Type, error)
Get functions should use a signature similar to the gorm [Where](https://github.com/go-gorm/gorm/blob/e57e5d8884d801caa4ce0307bcd081f7e889e514/chainable_api.go#L200) func like so:
```go
GetXYZ(query interface{}, args ...interface{}) ([]db.XYZ, err)
```
This will make the interface really flexible, and allows users of the interface to choose query and parameters. Granted it's a very thin layer, but it works for now. We can figure out what our query requirements are going to be as we tackle more complex use cases in the future and refactor this function as needed.

2023-09-26 20:12 UTC, isinyaaa commented
@lampajr are you sure you want you personal email in that `co-authored-by` tag? no problem by me, just a heads up

2023-09-27 09:56 UTC, lampajr commented
> @lampajr are you sure you want you personal email in that `co-authored-by` tag? no problem by me, just a heads up

@isinyaaa Thanks for the heads up but that is fine by me too, as this is the personal GitHub account I always used the primary email (which is the personal one)

2023-09-28 10:16 UTC, tarilabs commented on internal/service/db_service_test.go
> +	}
@lampajr just for the record this I realized was not behaving as intended, as `at0` and `at1` did in fact had the same ID (the invariant we wanted to check I think was having diff id, and for v1 to be > than v0, but it's not actually the case because https://github.com/opendatahub-io/model-registry/pull/36#pullrequestreview-1648369631)

2023-09-30 18:55 UTC, dhirajsb commented on internal/server/db_context.go
> +// TODO when refactoring to migrate to service/db_service usage, this should move inside service/ too.
Right, it should be moved to `internal/service/db_context.go`. Feel free to do so now.

2023-09-30 18:58 UTC, dhirajsb commented on internal/service/db_service.go
> +type TypeKind int32
We can reuse the enum from `db/type.go`.

2023-09-30 18:59 UTC, dhirajsb commented on internal/service/db_service_test.go
> +func setup(tmpFile *os.File) (*gorm.DB, error) {
No need for a tmpFile, SQLite supports an [in-memory DB](https://www.sqlite.org/inmemorydb.html).

2023-09-30 19:25 UTC, dhirajsb commented on internal/service/db_service_tx.go
> +package service
This can be moved into `internal/service/db_context.go`.

2023-10-02 09:15 UTC, tarilabs commented on internal/server/db_context.go
> +// TODO when refactoring to migrate to service/db_service usage, this should move inside service/ too.
Not really "free", I'm still prevented from merging this PR.

2023-10-02 09:53 UTC, tarilabs commented on internal/service/db_service_tx.go
> +package service
bb6415b

2023-10-02 09:53 UTC, tarilabs commented on internal/server/db_context.go
> +// TODO when refactoring to migrate to service/db_service usage, this should move inside service/ too.
bb6415b

2023-10-02 09:59 UTC, tarilabs commented on internal/service/db_service.go
> +type TypeKind int32
0b0d5ca

2023-10-02 10:14 UTC, tarilabs commented on internal/service/db_service_test.go
> +func setup(tmpFile *os.File) (*gorm.DB, error) {
👉  I do not share the same opinion as this requested change will prevent from running test in parallel (same DB "in memory" is used) but anyway 🤷 

/cc @lampajr to be noted ✍️ 

062e9a8

2023-10-03 22:28 UTC, dhirajsb commented on internal/service/db_service_test.go
> +func setup(tmpFile *os.File) (*gorm.DB, error) {
SQLite doesn't share the in-memory DB every call (even with the same connection string) creates a new in-memory DB.

2023-10-04 05:27 UTC, dhirajsb approved these changes
lgtm, just one small nitpick. Use non-sql operation verbs for services like these. So, `Create*` instead of `Insert*`, and `Get*` instead of `Read*`.

2023-10-04 06:16 UTC, tarilabs commented on internal/service/db_service_test.go
> +func setup(tmpFile *os.File) (*gorm.DB, error) {
> SQLite doesn't share the in-memory DB, every call (even with the same connection string) creates a new in-memory DB.

Again, that is not my understanding.

GORM manual suggest you use the connection string for memory sharing since GORM have connection pooling; so this is the reason of the function deferred to close up all connections, hence clearing the DB for the next one.

I've also tried using just `:memory:` so going _different_ from what advised in the GORM manual, and it has the downside one would expect: since as a downstream user you have no control over the connection, during test at times the DB is "cleared" from one orm call to the next one (specifically, DB tables were absent in subsequent calls).

2023-10-04 06:18 UTC, tarilabs commented
> (...) just one small nitpick. Use non-sql operation verbs for services like these. So, Create* instead of Insert*, and Get* instead of Read*.

We actually took care to implement as originally mentioned here: https://github.com/opendatahub-io/model-registry/pull/34#discussion_r1337335268

2023-10-04 08:17 UTC, lampajr approved these changes

2023-10-04 12:03 UTC, tarilabs commented
No longer vetos, approvals, proceeding to merge.

2023-10-04 12:04 UTC, merged