Implement MR service layer
opendatahub-io/model-registry-bf4-kf pull request #68
Opened 2023-10-11 12:50 UTC by lampajr

Fixes https://github.com/opendatahub-io/model-registry/issues/58

## Description

This PR aims to provide a first implementation of a Go-based model registry service layer, providing a minimal API based on the current `api/openapi/modelregistry.yml`.

Main aspects:
- `internal/model/registry/registry.gen.go` contains all types auto-generated from the openapi spec using [oapi-codegen](https://github.com/deepmap/oapi-codegen)
- `internal/core/mapper/mlmd_mapper.go` contains a simple Internal <--> MLMD model mapping.
- `internal/core/core.go` implements the core service layer named `ModelRegistryService` which provides a minimal API to:
  - Create/Get a `RegisteredModel`
  - Create/Get a `VersionedModel` (with `Artifacts` and generic metadata, if any)
- `examples` contains some tests we were able to setup showing how the service could be used.
  - `mr_service_example.go` simple usage example
  - `mr_service_test.go` shows an example of TestContainer based testing approach running the previous example against a mlmd test container
  - `mr_service_features_test.go` is an example of test using TestContainer and Cucumber

As an example for the Cucumber approach we implemented a simple User Story, here the result:

![image](https://github.com/opendatahub-io/model-registry/assets/26715795/e8df1093-7f8d-45ef-8c3d-7179a817672b)

## How Has This Been Tested?

This has been tested running the newly created test/examples under `examples` folder:

```bash
$ go test ./examples/... -v
```

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-10-13 16:05 UTC, isinyaaa reviewed
Just a preliminary review as I was skimming through the code.

Edit: put remarks on separate comments so we can discuss further.

2023-10-13 16:05 UTC, antisaling commented on examples/mr_service_example.go
> +func regiserModelVersion(service core.ModelRegistryApi, name string, version string, author string, uri string, format string) {
typo:

```suggestion
func registerModelVersion(service core.ModelRegistryApi, name string, version string, author string, uri string, format string) {
```

2023-10-13 16:05 UTC, antisaling commented on README.md
> +$ oapi-codegen -package registry -generate types api/openapi/modelregistry.yml >> internal/model/registry/registry.gen.go
Wouldn't it make more sense to

```suggestion
make gen/oapi_models
```

here?

Also, I prefer omitting the `$` as we're not providing the command output, so the user can simply copy the command from the box as is.

2023-10-13 16:05 UTC, antisaling commented on README.md
> +> **Note**: this step is automated in the Makefile `generate` step.
Also, there's no `generate` step, only `gen`, so it might generate some confusion, especially as we're only documenting the `build` step.

2023-10-13 16:05 UTC, antisaling commented on examples/mr_service_example.go
> +			panic(fmt.Sprintf("unknown level %v", lvl))
We should probably use a logging library here, though I see that neither `log` nor `glog` provide `Debug` logging. I found the [`logrus` package](https://pkg.go.dev/github.com/sirupsen/logrus) while looking for something but IDK whether it's worth the hassle to adopt it (I suppose we'd have to change logging in other parts of the code too) but [`go-grpc-middleware` supports that too](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus) ([example usage](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/main/interceptors/logging/examples/logrus/example_test.go)).

2023-10-13 16:05 UTC, antisaling commented on examples/mr_service_features_test.go
> +	}
do we want to setup the connection inside the test? I suppose this should be part of the setup function.

2023-10-13 16:07 UTC, isinyaaa commented
I'd separate the functionality of Mapper as the two uses are pretty distinct, i.e. MLMD -> Internal conversion would be separate from Internal -> MLMD.

2023-10-13 16:30 UTC, lampajr commented on README.md
> +> **Note**: this step is automated in the Makefile `generate` step.
+1 just a typo, thanks for spotting it

2023-10-16 06:57 UTC, lampajr commented on examples/mr_service_example.go
> +			panic(fmt.Sprintf("unknown level %v", lvl))
I definitely agree on switching to use some ad-hoc logging libraries, for now I just used the same approach that was used in other files. I wouldn't pay too much attention on this as this is just for the example.

Anyway `go-grpc-middleware` looks pretty much interesting, will give it a look :)

2023-10-16 07:00 UTC, lampajr commented on examples/mr_service_features_test.go
> +	}
from my understanding this is part of `iHaveAConnectionToMR` which is a precondition of the Cucumber test, therefore it can be seen exactly as a setup here. @tarilabs is my understanding correct?

2023-10-16 07:05 UTC, tarilabs commented on examples/mr_service_features_test.go
> +	}
I would expect is not the responsibility of the "core/service" layer to setup the connection to grpc opaquely, so yes like the example already build a connection and passes over the the core-layer, same happens in testing.

This is what I understood we wanted to create with the core-layer.
For analogy, the "DAL" worked in the same way (it did not setup the gorm/db connection opaquely).

I am always open to consider refactorings if we change our mind.

2023-10-16 07:07 UTC, tarilabs submitted a review, later dismissed
fwiw I've made use of this core/service layer while contributing TestContainers and cucumber testing. The core/service layer works for me. While I was not part of reviewer (since already contributed commits here) now recording my approval since github switched me as "commenter only" as participating in the discussion, so tidying that up.

2023-10-18 08:03 UTC, lampajr commented
As agreed we are going to rebase this PR from the [OpenAPI refactoring one](https://github.com/opendatahub-io/model-registry/pull/66) - this is going to slightly change the generated models and api.

2023-10-18 16:38 UTC, lampajr commented on examples/mr_service_example.go
> +			panic(fmt.Sprintf("unknown level %v", lvl))
no longer used in the tests

2023-10-18 16:44 UTC, tarilabs commented on internal/core/api.go
> +type ModelRegistryApi interface {
In this API, we opted to use `[]*openapi.<entity>, ListResult` as part of the return tuple; alternatively, we thought about this structure. We thought about leaving it as a comment for the evaluation.

2023-10-19 06:50 UTC, dhirajsb requested changes
Added comments for re-using `*List` types, make target, and renaming `VersionedModel` in tests. 
Otherwise it looks good. Nice work with testcontainers. :+1:

2023-10-19 06:50 UTC, dhirajsb commented on internal/core/api.go
> +type ModelRegistryApi interface {
We could also re-use the `*List` types from `internal/model/openapi`. It'll be one less thing to map in `api_model_registry_service_service.go`

2023-10-19 06:50 UTC, dhirajsb commented on test/bdd/features/example.feature
> +    When I store a RegisteredModel with name "Pricing Model" and a child VersionedModel with name "v1" and a child Artifact with uri "s3://12345"
Replace `VersionedModel` with `ModelVersion`. There are also other places in the code where it needs to be changed.

2023-10-19 06:50 UTC, dhirajsb commented on Makefile
> +.PHONY: clean-test
The target name `clean-test` is confusing because `clean` is another target in the file. Can we use a better name to be explicit?

2023-10-19 06:55 UTC, tarilabs commented on test/bdd/features/example.feature
> +    When I store a RegisteredModel with name "Pricing Model" and a child VersionedModel with name "v1" and a child Artifact with uri "s3://12345"
Ah, I missed it, sorry. Nice catch! 🏗️

2023-10-19 07:44 UTC, tarilabs commented on test/bdd/features/example.feature
> +    When I store a RegisteredModel with name "Pricing Model" and a child VersionedModel with name "v1" and a child Artifact with uri "s3://12345"
done with b4ec1466043e561c2541ba4402878fbcbde24783

2023-10-19 07:51 UTC, lampajr commented on Makefile
> +.PHONY: clean-test
you are definitely right, it could be quite confusing.

Updated to a more explicit `test-nocache` with 515228e1a02769bbf442c7fd9a8a511b5e28196f.

2023-10-19 08:49 UTC, tarilabs commented
> We could also re-use the *List types from internal/model/openapi. It'll be one less thing to map in api_model_registry_service_service.go

Done with c6449f4

2023-10-19 14:39 UTC, dhirajsb approved these changes
lgtm

2023-10-19 23:57 UTC, isinyaaa commented on internal/core/core.go
> +		filterQuery = fmt.Sprintf("name = \"%s\"", *name)
The client doesn't know that we're prefixing the ModelVersion name with a RegisteredModel id in MLMD

2023-10-20 06:54 UTC, lampajr commented on internal/core/core.go
> +		filterQuery = fmt.Sprintf("name = \"%s\"", *name)
That is correct but for now we "assumed" that it is known.
Once https://github.com/opendatahub-io/model-registry/issues/76 got fixed we can use the `registeredModelId` to ignore the previous assumption and let user provide just model version.

2023-10-20 07:13 UTC, lampajr commented
As agreed yesterday, going to merge as first service layer iteration.

2023-10-20 07:13 UTC, merged