Setup image build and push to quay
opendatahub-io/model-registry-bf4-kf pull request #72
Opened 2023-10-16 10:57 UTC by lampajr

Fixes https://github.com/opendatahub-io/model-registry/issues/15

## Description
Created two GitHub workflows automating the container image build and push to quay.io registry.
I preferred to keep `main` and `pr` checks separated to avoid adding conditional workflows that could become confusing and hard to maintain.

Therefore I created a separated `build-image` action that takes care of building the image and pushing it to quay if needed. Then both workflows use that action with different inputs.
 
Main differences between the two workflows:
- `main`: push the generated image using with three different tags, `latest`, `main` and `<commit>`
- `pr`: performs a build for the PR branch and skip the whole push step.

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-10-16 11:08 UTC, lampajr commented on .github/workflows/build-image-pr.yml
> +  pull_request_target:
As per my findings I had to set `pull_request_target` in order to access repository secrets, therefore this workflow is not going to be triggered in this PR as it needs to be merged first for security reasons.

2023-10-16 12:33 UTC, tarilabs reviewed
Thank you so much!!

Just some open questions:

2023-10-16 12:33 UTC, tarilabs commented on .github/workflows/build-image-pr.yml
> +  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
I agree the "-pr" to not push to Quay, I understand you might need to supply some values for `QUAY_USERNAME` and `QUAY_PASSWORD` but to avoid security-related-questions, can't we either omit them completely here or set them to some dummy values? See other comment about `action.yml`

2023-10-16 12:33 UTC, tarilabs commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
to avoid the need of login, shouldn't we guard this with `SKIP_IF_EXISTING == 'true' || inputs.PUSH == 'true'` ?

That way, if the caller GHA does set
```yaml
        with:
          SKIP_IF_EXISTING: false
// ...
          PUSH: false
```

as the `-pr.yml` action below, you don't need to supply user/psw?

2023-10-16 13:02 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
I definitely agree on this, as long as we don't push anything it would be better to completely skip that step.
Going to apply the fix

2023-10-16 13:06 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
acutally I think that `inputs.PUSH == 'true'` is enough as guard.

2023-10-16 13:08 UTC, tarilabs commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
> acutally I think that `inputs.PUSH == 'true'` is enough as guard.

Oh I see, the "Check if Image already exists" uses curl directly, not docker/podman commands; I agree

2023-10-16 13:13 UTC, tarilabs approved these changes, later dismissed
thank you so much

2023-10-16 13:13 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
Resolved by 5548703ce333854a319650a016b672b1707cac96. Given that we skip the login I reverted the trigger event to `pull_request`

2023-10-16 13:14 UTC, lampajr commented on .github/workflows/build-image-pr.yml
> +  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
Resolved by 5548703ce333854a319650a016b672b1707cac96

2023-10-16 13:14 UTC, tarilabs commented on .github/workflows/build-image-pr.yml
> +  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
was resolved with 5548703

2023-10-16 13:14 UTC, tarilabs commented on .github/actions/build-image/action.yml
> +        password: ${{ env.QUAY_PASSWORD }}
was resolved with 5548703

2023-10-16 13:14 UTC, lampajr commented on .github/workflows/build-image-pr.yml
> +  pull_request_target:
As we don't push anything from PR checks we don't even need to login to registry, therefore we do not need to access the secrets.

Reverted to `pull_request` event.

2023-10-19 15:39 UTC, dhirajsb requested changes

2023-10-19 15:39 UTC, dhirajsb commented on .github/actions/build-image/action.yml
> +        tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
@lampajr let's put this logic in a shell script. That'll make it re-usable in a non-github action build like downstream and managed services builds.

2023-10-19 15:42 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
you mean the whole step or just the command to get all tags `tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')` ? I guess the latter right?

2023-10-19 16:46 UTC, dhirajsb commented on .github/actions/build-image/action.yml
> +        tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
I was thinking we could create something like rhosak [build_deploy.sh](https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/build_deploy.sh)

2023-10-20 10:17 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
I see your point and make sens to have a script doing the same build and push - I am working on this. Moreover I'd like to incorporate some of the sub tasks in the Makefile as well (like `docker build` and `docker push`) similarly to what has been done in the script you shared

2023-10-20 14:01 UTC, lampajr commented on .github/workflows/build-image-pr.yml
> +  pull_request_target:
As we are going to run an internal script that can pushes on the registry I would prefer to keep `pull_request_target` to avoid malicious code execution on external PR.

Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

```
This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow
```

2023-10-20 14:03 UTC, lampajr commented on .github/actions/build-image/action.yml
> +        tags=$(curl --request GET 'https://quay.io/api/v1/repository/${{ env.QUAY_ORG }}/${{ inputs.IMAGE_REPO }}/tag/?specificTag=${{ env.TARGET_IMAGE_TAG }}')
I was able to extract the build & deploy stuff in a dedicated script, I also put some of the tasks in the Makefile as anticipated.

2023-10-20 14:07 UTC, lampajr commented on .github/workflows/build-image-pr.yml
> +  pull_request_target:
Therefore the PR build image workflow is not going to be executed in this PR, as it need to get merged first.
I tried locally and it worked:
```bash
act --env QUAY_ORG=alampare -W .github/workflows/build-image-pr.yml
```

![image](https://github.com/opendatahub-io/model-registry/assets/26715795/c947193b-e7ef-4a28-a0f6-c63b90bfccf4)

2023-10-23 19:00 UTC, dhirajsb approved these changes
/lgtm

2023-10-23 19:00 UTC, merged