Manage prefix for owned entities
opendatahub-io/model-registry-bf4-kf pull request #79
Opened 2023-10-20 12:27 UTC by tarilabs

Resolves #78 
Follows up on https://github.com/opendatahub-io/model-registry/pull/68#discussion_r1366550044
Also aligns to name mapping as showcased in #77 

## Description
Address acceptance criterias in #78 

## How Has This Been Tested?
```
go test ./internal/... 
go test ./test/... 
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-10-20 12:48 UTC, lampajr submitted a review, later dismissed

2023-10-24 05:29 UTC, dhirajsb requested changes

2023-10-24 05:29 UTC, dhirajsb commented on internal/core/api.go
> +	GetModelArtifactByParams(artifactName *string, modelVersionId *BaseResourceId, externalId *string) (*openapi.ModelArtifact, error)
There is clearly a pattern forming here. We need to rename `registeredModelId` parameter to `parentContextId` and re-use it for all resources that may need to have a search performed in a parent context. If we want to avoid using `context`, we can call it `parentResourceId` instead.

2023-10-24 12:10 UTC, tarilabs commented on internal/core/api.go
> +	GetModelArtifactByParams(artifactName *string, modelVersionId *BaseResourceId, externalId *string) (*openapi.ModelArtifact, error)
Not sure I fully understood the required-change here, given the comment on the "implicit Go interface"; what I got, I renamed the parameter per your request with d1d7c88.
If you intended something different, kindly let me know please. Thanks in advance.

2023-10-24 15:10 UTC, dhirajsb approved these changes
/lgtm

2023-10-24 19:11 UTC, lampajr approved these changes

2023-10-25 07:31 UTC, tarilabs commented
two approvals, no vetos, proceeding to merge.

2023-10-25 07:31 UTC, merged