Add in REST findModelArtifact modelVersionID query param
opendatahub-io/model-registry-bf4-kf pull request #81
Opened 2023-10-20 14:07 UTC by tarilabs

Resolves #80 

## Description
Address acceptance criteria in #80 

## How Has This Been Tested?
Tested with Swagger editor at: https://editor.swagger.io

You can preview with: https://editor.swagger.io/?url=https://raw.githubusercontent.com/opendatahub-io/model-registry/1c8ba43ebb47690a258cce29efd22cf5ea22fa90/api/openapi/model-registry.yaml#operations-ModelRegistryService-findModelArtifact

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-10-20 14:23 UTC, lampajr submitted a review, later dismissed

2023-10-24 05:30 UTC, dhirajsb requested changes

2023-10-24 05:30 UTC, dhirajsb commented on api/openapi/model-registry.yaml
> +    modelVersionID:
As mentioned in #79 we should instead create either `parentContextId` or `parentResourceId` parameter for all parent context based search endpoints.

2023-10-24 12:21 UTC, tarilabs commented on api/openapi/model-registry.yaml
> +    modelVersionID:
As I understood from this required-change, I folded the 2 parameters into a single parentResourceID parameter for both, with 2f9b54a
👉 https://github.com/opendatahub-io/model-registry/pull/81#event-10753203936

2023-10-24 15:06 UTC, dhirajsb approved these changes
/lgtm

2023-10-24 19:12 UTC, lampajr approved these changes
lgtm

2023-10-25 07:32 UTC, merged

2023-10-25 07:32 UTC, tarilabs commented
two approvals, no veto, proceeding to merge